### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by phuocding** [phuocding/master-to-pythonista#2]
You can choose this issue to upgrade a concise README

**Comment by ahmad-shiddiq** [comment]
Can I try to make this more UX friendly?

**Comment by phuocding** [comment]
> Can I try to make this more UX friendly?

Yes, you can. You always welcome

**Comment by ahmad-shiddiq** [comment]
Thanks, I'm on work at this.

**Comment by phuocding** [comment]
> Thanks, I'm on work at this.

pull my latest update and enjoy it! Many thanks

**Comment by ahmad-shiddiq** [comment]
I'm done with that, please see at #15 
I see that cannot be auto-merge, I didn't too understand about that, sorry.

**Comment by phuocding** [comment]
> I'm done with that, please see at #15
> I see that cannot be auto-merge, I didn't too understand about that, sorry.

Please "git pull" my latest update version and refactor again. Thanks

**Comment by ahmad-shiddiq** [comment]
I'm so sorry, I won't work on this repo again. Thanks.
